FROM node:lts-fermium
ARG CI_ENVIRONMENT_NAME
ENV CI_ENVIRONMENT_NAME=$CI_ENVIRONMENT_NAME
ARG GITLAB_AUTH_TOKEN
ENV GITLAB_AUTH_TOKEN=$GITLAB_AUTH_TOKEN
ADD . /app/sempu
WORKDIR /app/sempu

RUN npm install && npm run build-${CI_ENVIRONMENT_NAME}
EXPOSE 3000

CMD ["sh", "-c", "npm run ${CI_ENVIRONMENT_NAME}"]
