# Default values for master.
# This is a YAML-formatted file.

# The overall system your service is a part of
system: sempu
# The name of your service
service: sempu
# The major version number for your service
version: 1
release: sempu-v0.0.1

# Docker settings
image:
  # The name of your docker container
  repository: harbor.linkaja.com/lab/sempu
  # Your docker container's tag
  tag: latest
  imagePullPolicy: IfNotPresent

# Istio uses the service account name as a component of the service's security
# identity. Set "create" to false to use an previously created service account.
serviceAccount:
  name: sempu
  create: true

imagePullSecrets:
  name: harbor-cred-cms

# The initial number of pod replicas to run for your service
replicaCount: 1
# The maximum number of pods from that set that can be unavailable at once
maxUnavailable: 1

# Horizontal pod autoscaler configuration (optional)
autoscaling:
  minReplicas: 1
  maxReplicas: 5
  targetAverageCpuUtilization: 80

# Port settings
# Ports must be named <protocol>[-<suffix>] to work with Istio.
# Valid protocols are grpc, http, http2, https, mongo, mysql, redis, tcp, tls, udp
ports:
  - name: sempu-svc
    port: 3000
    targetPort: 3000
  # - name: http-status
  #   port: 8080
  #   targetPort: 8080

# Configure the Istio ingress gateway to route outside traffic for the provided
# host name to this service on the ports and protocols defined in the 'ports' section
# above.
ingressGateway:
  name: istio-system/ingress-private-https
  host: linkage-dev.linkaja.com
  matchPrefix:
    - '/'
    # - "/bar"

# The overall timeout for requests to this service
# Optional
overallTimeout: 180s

# Client retry settings (use Istio syntax)
# Optional
retries:
  attempts: 3
  perTryTimeout: 60s

# Circuit breaker settings (use Istio syntax)
# Optional
outlierDetection:
  consecutive5xxErrors: 5

# Resource settings (use Kubernetes syntax)
# Optional
resources:
  requests:
    memory: '64Mi'
    cpu: '250m'
  limits:
    memory: '128Mi'
    cpu: '500m'

# Probe settings (use Kubernetes syntax)
# Optional
probes:
  livenessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /ping
      port: 3000
  readinessProbe:
    timeoutSeconds: 180
    httpGet:
      path: /ping
      port: 3000

configMap:
  enabled: false
  # Where the config map should be mounted inside your container's filesystem.
  # mountPath: /app/.env
  # subPath: .env
  # fileName: .env
  # Everything under content is copied verbatim into your service's configmap.
  # content:
  #   key1: value1
  #   key2: value2
